apiVersion: protection.crossplane.io/v1beta1
kind: Usage
metadata:
  name: ipv6assignment-uses-ipv6
  namespace: crossplane-system
spec:
  of:
    apiVersion: reservedipv6.digitalocean.m.crossplane.io/v1alpha1
    kind: IPv6
    resourceRef:
      name: example-crossplane-ipv6
  by:
    apiVersion: reservedipv6.digitalocean.m.crossplane.io/v1alpha1
    kind: IPv6Assignment
    resourceRef:
      name: example-crossplane-ipv6assignment
---
apiVersion: protection.crossplane.io/v1beta1
kind: Usage
metadata:
  name: ipv6assignment-uses-droplet
  namespace: crossplane-system
spec:
  of:
    apiVersion: droplet.digitalocean.m.crossplane.io/v1alpha1
    kind: Droplet
    resourceRef:
      name: example-crossplane-droplet
  by:
    apiVersion: reservedipv6.digitalocean.m.crossplane.io/v1alpha1
    kind: IPv6Assignment
    resourceRef:
      name: example-crossplane-ipv6assignment
