// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/eaglesemanation/provider-digitalocean/apis/namespaced/image/v1alpha1"
	v1alpha11 "github.com/eaglesemanation/provider-digitalocean/apis/namespaced/sshkey/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Droplet.
func (mg *Droplet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Image),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ImageRef,
		Selector:     mg.Spec.ForProvider.ImageSelector,
		To: reference.To{
			List:    &v1alpha1.ImageList{},
			Managed: &v1alpha1.Image{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Image")
	}
	mg.Spec.ForProvider.Image = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ImageRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SSHKeys),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.SSHKeysRefs,
		Selector:      mg.Spec.ForProvider.SSHKeysSelector,
		To: reference.To{
			List:    &v1alpha11.KeyList{},
			Managed: &v1alpha11.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SSHKeys")
	}
	mg.Spec.ForProvider.SSHKeys = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SSHKeysRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Image),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ImageRef,
		Selector:     mg.Spec.InitProvider.ImageSelector,
		To: reference.To{
			List:    &v1alpha1.ImageList{},
			Managed: &v1alpha1.Image{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Image")
	}
	mg.Spec.InitProvider.Image = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ImageRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.SSHKeys),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.SSHKeysRefs,
		Selector:      mg.Spec.InitProvider.SSHKeysSelector,
		To: reference.To{
			List:    &v1alpha11.KeyList{},
			Managed: &v1alpha11.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SSHKeys")
	}
	mg.Spec.InitProvider.SSHKeys = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SSHKeysRefs = mrsp.ResolvedReferences

	return nil
}
