// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/eaglesemanation/provider-digitalocean/apis/cluster/droplet/v1alpha1"
	v1alpha1image "github.com/eaglesemanation/provider-digitalocean/apis/cluster/image/v1alpha1"
	v1alpha1reservedip "github.com/eaglesemanation/provider-digitalocean/apis/cluster/reservedip/v1alpha1"
	v1alpha1reservedipv6 "github.com/eaglesemanation/provider-digitalocean/apis/cluster/reservedipv6/v1alpha1"
	v1alpha1sshkey "github.com/eaglesemanation/provider-digitalocean/apis/cluster/sshkey/v1alpha1"
	v1alpha1cluster "github.com/eaglesemanation/provider-digitalocean/apis/cluster/v1alpha1"
	v1beta1 "github.com/eaglesemanation/provider-digitalocean/apis/cluster/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1image.SchemeBuilder.AddToScheme,
		v1alpha1reservedip.SchemeBuilder.AddToScheme,
		v1alpha1reservedipv6.SchemeBuilder.AddToScheme,
		v1alpha1sshkey.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
