// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Droplet.
func (mg *Droplet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Image),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ImageRef,
		Selector:     mg.Spec.ForProvider.ImageSelector,
		To: reference.To{
			List:    &ImageList{},
			Managed: &Image{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Image")
	}
	mg.Spec.ForProvider.Image = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ImageRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SSHKeys),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.SSHKeysRefs,
		Selector:      mg.Spec.ForProvider.SSHKeysSelector,
		To: reference.To{
			List:    &KeyList{},
			Managed: &Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SSHKeys")
	}
	mg.Spec.ForProvider.SSHKeys = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SSHKeysRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Image),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ImageRef,
		Selector:     mg.Spec.InitProvider.ImageSelector,
		To: reference.To{
			List:    &ImageList{},
			Managed: &Image{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Image")
	}
	mg.Spec.InitProvider.Image = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ImageRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.SSHKeys),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.SSHKeysRefs,
		Selector:      mg.Spec.InitProvider.SSHKeysSelector,
		To: reference.To{
			List:    &KeyList{},
			Managed: &Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SSHKeys")
	}
	mg.Spec.InitProvider.SSHKeys = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SSHKeysRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this IP.
func (mg *IP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DropletIDRef,
		Selector:     mg.Spec.ForProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DropletID")
	}
	mg.Spec.ForProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DropletIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DropletIDRef,
		Selector:     mg.Spec.InitProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DropletID")
	}
	mg.Spec.InitProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DropletIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPAssignment.
func (mg *IPAssignment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DropletIDRef,
		Selector:     mg.Spec.ForProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DropletID")
	}
	mg.Spec.ForProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DropletIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPAddress),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IPAddressRef,
		Selector:     mg.Spec.ForProvider.IPAddressSelector,
		To: reference.To{
			List:    &IPList{},
			Managed: &IP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IPAddress")
	}
	mg.Spec.ForProvider.IPAddress = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IPAddressRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DropletIDRef,
		Selector:     mg.Spec.InitProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DropletID")
	}
	mg.Spec.InitProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DropletIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IPAddress),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IPAddressRef,
		Selector:     mg.Spec.InitProvider.IPAddressSelector,
		To: reference.To{
			List:    &IPList{},
			Managed: &IP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IPAddress")
	}
	mg.Spec.InitProvider.IPAddress = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IPAddressRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPv6Assignment.
func (mg *IPv6Assignment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DropletIDRef,
		Selector:     mg.Spec.ForProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DropletID")
	}
	mg.Spec.ForProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DropletIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IP),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IPRef,
		Selector:     mg.Spec.ForProvider.IPSelector,
		To: reference.To{
			List:    &IPv6List{},
			Managed: &IPv6{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IP")
	}
	mg.Spec.ForProvider.IP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IPRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.DropletID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DropletIDRef,
		Selector:     mg.Spec.InitProvider.DropletIDSelector,
		To: reference.To{
			List:    &DropletList{},
			Managed: &Droplet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DropletID")
	}
	mg.Spec.InitProvider.DropletID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DropletIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IP),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IPRef,
		Selector:     mg.Spec.InitProvider.IPSelector,
		To: reference.To{
			List:    &IPv6List{},
			Managed: &IPv6{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IP")
	}
	mg.Spec.InitProvider.IP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IPRef = rsp.ResolvedReference

	return nil
}
